
```
1. Convert the given list into a numpy array and replace the odd elements with -2.
Lst=[[1,2,3], [4,5,6], [7,8,9]]
```

In [6]:
import numpy as np
lst = [[1,2,3], [4,5,6], [7,8,9]]
arr = np.array(lst)
arr[arr%2 != 0] = -2
arr

array([[-2,  2, -2],
       [ 4, -2,  6],
       [-2,  8, -2]])

```
2. In the numpyarray given below print all the elements ranging from 8 to 15.

arr = [1,2,3,4,5,8,9,10,12,22,32,54,99,6,7]
```

In [11]:
arr2 = np.array([1,2,3,4,5,8,9,10,12,22,32,54,99,6,7])
x = arr2[(arr2 > 7) & (arr2 < 16)]
print(x)

[ 8  9 10 12]


```
3. Create a 3*3 narray thatincludes numbersfrom 1 to 9 and swap columns1 and2
```

In [13]:
arr3 = np.arange(1, 10).reshape(3,3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr3[:, [0, 1]] = arr3[:, [1, 0]]
arr3

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

```
In the given numpyarray replace the NaN values with the average of columns
arr= np.array([[1.3, 2.5, 3.6, np.nan], [2.6, 3.3, np.nan, 5.5], [2.1, 3.2, 5.4, 6.5]])
```

In [72]:
arr4= np.array([[1.3, 2.5, 3.6, np.nan], [2.6, 3.3, np.nan, 5.5], [2.1, 3.2, 5.4, 6.5]])
col_mean = np.nanmean(arr4, axis=0)
print(col_mean)

inds = np.where(np.isnan(arr4))

print("\n", arr4[inds], inds[1], "\n")

arr4[inds] = np.take(col_mean, inds[1])

print(arr4)

[2.  3.  4.5 6. ]

 [nan nan] [3 2] 

[[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


```
5. For the numpyarray given below perform the following operation:i.Convert the numpyarray into a numpymatrixii.Sort the values in a matrix
arr = [[2,4,6],[1,3,5]]
```

In [80]:
arr5 = np.array([[2,4,6],[1,3,5]])
m1 = np.asmatrix(arr5)
m1.sort(axis=0)

In [81]:
m1

matrix([[1, 3, 5],
        [2, 4, 6]])