In [6]:
#Creating numpy Arrays
import numpy as np
arr=np.array([45,63,98,78,17]) #one dim
arr=np.array((10,20,30,40,50))
print(arr)
print(type(arr))
print(arr.dtype)

[10 20 30 40 50]
<class 'numpy.ndarray'>
int32


In [8]:
arr=np.array([45,63,98,78,17,12.99])
print(arr)
print(arr.dtype)

[45.   63.   98.   78.   17.   12.99]
float64


In [12]:
#Zeros(), once()
a=np.zeros(5)
print(a)
a=np.ones(6)
print(a)

a=np.ones(6,dtype='int')
print(a)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1]


In [17]:
#arange() [start,stop,step]
#a=np.arange(2,10)
a=np.arange(2.5,10.4)
print(a)
print(type(a))

[2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
<class 'numpy.ndarray'>


In [16]:
a=range(2,10)
print(list(a))

[2, 3, 4, 5, 6, 7, 8, 9]


In [21]:
#two dimensional
arr_1d=np.array([45,63,98,78,17,12])
arr_2d=np.array([[10,20,30,100],[40,50,60,400],[70,80,90,300]])
print(arr)   #3x3

[[ 10  20  30 100]
 [ 40  50  60 400]
 [ 70  80  90 300]]


In [24]:
#indexing
print(arr_1d[2])
print(arr_2d[2][1])  #[row][col]

98
80


In [28]:
arr_2d=np.array([[10,20,30,100],[40,50,60,400],[70,80,90,300]])
print("Dimentions:",arr_2d.ndim)
print("Size:",arr_2d.size)
print("Shape:",arr_2d.shape)
print("Item Size(byte):",arr_2d.itemsize)

Dimentions: 2
Size: 12
Shape: (3, 4)
Item Size(byte): 4


In [29]:
#Array Multiplication
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[10,11],[20,21],[30,31]])
arr=np.dot(arr1,arr2)
print(arr)

[[140 146]
 [320 335]]


In [31]:
arr1=np.array([[1,2,3,10],[4,5,6,20]])
arr2=np.array([[10,11],[20,21],[30,31]])
arr=np.dot(arr1,arr2)
print(arr)

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [ ]:
#Hill-Cipher

In [33]:
#Import data from file
import numpy as np
data=np.loadtxt("marks.csv",delimiter=',',usecols=(5),skiprows=1,dtype='int')
print(data)
print(type(data))

[420 280 350 269 317 470 333 365 305 350 460 474 409 377 415 382 298 462
 370 313 464 302 252 259 308 392 424 403 370 328 398 434 291 472 263 439
 464 449 401 364 296 292 438 357 331 317 429 407 321 274 447 274 437 411
 257 310 396 270 311 459 378 316 283 266 381 409 313 306 448 348 292 400
 352 441 428 309 441 439 264 281 302 432 423 336 383 321 469 270 341 281
 403 333 323 348 345 397 449 261 456 370 322 379 446 404 301 254 351 444
 264 286 463 273 316 324 465 398 324 340 414 346 408 332 394 474 398 262
 410 391 444 461]
<class 'numpy.ndarray'>


In [39]:
#Aggregate Functions in Numpy
print("Sum of Marks:",data.sum())
print("Min:",data.min())
print("Max:",data.max())
print("Avg Marks:",data.mean())
print("standard Deviations:",data.std())
print("Variance:",data.var())

Sum of Marks: 47356
Min: 252
Max: 474
Avg Marks: 364.2769230769231
standard Deviations: 66.17947803971762
Variance: 4379.723313609467


In [44]:
#Reshaping array
a = np.array([3,6,9,12,15,96])
print(a)
print("Shape of a:",a.shape)
b = a.reshape(2,3)
print(b)
print("Shape of b:",b.shape)

#a=np.array([3,6,9,12,63])
#b = a.reshape(2,5)
#print(b) #Error ! can not reshape

c=b.flatten()   #ravel()
print(c)

[ 3  6  9 12 15 96]
Shape of a: (6,)
[[ 3  6  9]
 [12 15 96]]
Shape of b: (2, 3)
[ 3  6  9 12 15 96]


In [47]:
#Transpose
print(b)  #2x3
c=b.transpose()
print(c)  #3x2

[[ 3  6  9]
 [12 15 96]]
[[ 3 12]
 [ 6 15]
 [ 9 96]]


In [50]:
#Joining(Stacking) arrays
arr1 = np.array(( 1, 2, 3 ))
print ("1st Input array : \n", arr1) 
  
arr2 = np.array(( 4, 5, 6 ))
print ("2nd Input array : \n", arr2) 
  
#Verticle stacking
out_arr = np.stack((arr1, arr2))  #Normal Stacking
print ("Output verticle stacked array:\n ", out_arr)

#Horizontal stacking(Concatenation)
out_arr = np.hstack((arr1, arr2))  #not Normal Stacking
print ("Output horizontal stacked array:\n ", out_arr)


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output verticle stacked array:
  [[1 2 3]
 [4 5 6]]
Output horizontal stacked array:
  [1 2 3 4 5 6]


In [52]:
arr1 = np.array([[10,20,30],[100,200,300]])
print ("1st Input array : \n", arr1) 
  
arr2 = np.array([[40,50,60],[400,500,600]])
print ("2nd Input array : \n", arr2) 

out_arr = np.vstack([arr1, arr2])  #not Normal Stacking
print ("Output Vertical stacked array:\n ", out_arr)

1st Input array : 
 [[ 10  20  30]
 [100 200 300]]
2nd Input array : 
 [[ 40  50  60]
 [400 500 600]]
Output Vertical stacked array:
  [[ 10  20  30]
 [100 200 300]
 [ 40  50  60]
 [400 500 600]]


In [53]:
#Fancy Indexing, we can pass array of indices to access multiple array values
a=np.array([3,78,23,12,56,96,78,25,34,78,14,19])
print(a[10])  #Normal indexing

ind=np.array([[3,4,5],[7,10,6]])
print(a[ind]) #Fancy indexing

14
[[12 56 96]
 [25 14 78]]


In [55]:
#Broadcasting of Operations
lst=[10,20,30]
print(lst*3)
ar=np.array(lst)
print(ar*3)

[10, 20, 30, 10, 20, 30, 10, 20, 30]
[30 60 90]


In [56]:
#Broadcasting airthmetical operations on ndarray
#Operation is always applied to each element of the array
A=np.array([45,68,93,12])
new_A=A*10
print(new_A)
new_A1=A**2
print(new_A1)

[450 680 930 120]
[2025 4624 8649  144]


In [57]:
#Slicing
a=np.array([3,78,23,12,56,96,78,25,34,78,14,19])
#slice start,stop,step
print(a[2:8])

[23 12 56 96 78 25]


In [59]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])  #3x5
print(a)
print(a[1:,2:5])
print(a[0:2,0:2]) #[row slice,col slice]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 8  9 10]
 [13 14 15]]
[[1 2]
 [6 7]]


In [60]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
for i in a:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [61]:
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
